import std/[os, strutils]

import test_support

compileBinary()

# A template applied once is a copy. These cover the part that makes it a template: knowing what was
# generated, so a later change to the template can be told apart from an edit made here.
let root = "/tmp/wing-tplupdate"
let templateDir = root / "demo"
let projectDir = root / "app"
resetDir(root)
createDir(templateDir)
writeFile(templateDir / "template.lua", """
local wing = require("wing")
wing.template("demo", { description = "a demo", language = "text" })
""")
writeFile(templateDir / "README.md", "hello {{project_name}}\n")
writeFile(templateDir / "keep.txt", "untouched\n")

let envPrefix = freshEnv("tplupdate") & "WING_TEMPLATE_DIR=" &
    quoteShell(root) & " "
let wing = wing(envPrefix)
discard checked(wing & "init")
discard checked(wing & "template builtins install --force")
discard checked(wing & "template apply demo " & quoteShell(projectDir) &
    " --name sample --no-git")

# --- what generated it is written into it ------------------------------------
doAssert fileExists(projectDir / ".wing.toml"), "a generated project records its template"
let record = readFile(projectDir / ".wing.toml")
doAssert record.contains("template = \"demo\""), record
doAssert record.contains("name = \"sample\""), record
doAssert record.contains("[[files]]"), "the record has to carry per-file hashes"

# --- nothing has changed yet --------------------------------------------------
let fresh = run(wing & "template check " & quoteShell(projectDir))
doAssert fresh.code == 0, fresh.output
doAssert fresh.output.contains("Up to date"), fresh.output

# --- the template moves, and the project has an edit of its own ---------------
writeFile(templateDir / "README.md", "hello {{project_name}}\nand a new line\n")
writeFile(templateDir / "NEW.md", "arrived later\n")
writeFile(projectDir / "keep.txt", "untouched, then edited here\n")

let drifted = run(wing & "template check " & quoteShell(projectDir))
doAssert drifted.code != 0, "a project behind its template is not up to date"
doAssert drifted.output.contains("README.md"), drifted.output
doAssert drifted.output.contains("NEW.md"), drifted.output
# The edited file is reported as the project's own, not as something to overwrite.
doAssert drifted.output.contains("yours"), drifted.output

# --- update takes the template's changes and leaves the edit alone ------------
let updated = checked(wing & "template update " & quoteShell(projectDir))
doAssert updated.contains("README.md"), updated
doAssert readFile(projectDir / "README.md").contains("and a new line")
doAssert fileExists(projectDir / "NEW.md")
doAssert readFile(projectDir / "keep.txt").contains("edited here"),
    "an edit here must survive an update"

# Running it again finds nothing, and the edit is still the project's own rather than a difference
# the next update would revert.
let after = checked(wing & "template check " & quoteShell(projectDir))
doAssert after.contains("Up to date"), after
doAssert after.contains("yours"), after

# --- a file changed in both places is a conflict, and is not taken by default --
writeFile(templateDir / "keep.txt", "the template moved too\n")
let conflicted = run(wing & "template check " & quoteShell(projectDir))
doAssert conflicted.output.contains("conflict"), conflicted.output
discard checked(wing & "template update " & quoteShell(projectDir))
doAssert readFile(projectDir / "keep.txt").contains("edited here"),
    "a conflict is left alone unless --force"
discard checked(wing & "template update " & quoteShell(projectDir) & " --force")
doAssert readFile(projectDir / "keep.txt").contains("the template moved too"),
    "--force takes the template's side"

# --- diff shows what would change, and changes nothing ------------------------
writeFile(templateDir / "README.md", "hello {{project_name}}\nand a third line\n")
let before = readFile(projectDir / "README.md")
let diffed = checked(wing & "template diff " & quoteShell(projectDir))
doAssert diffed.contains("third line"), diffed
doAssert readFile(projectDir / "README.md") == before, "diff must not write anything"

# --- a directory wing did not generate says so --------------------------------
let stranger = "/tmp/wing-tplupdate-stranger"
resetDir(stranger)
let refused = run(wing & "template check " & quoteShell(stranger))
doAssert refused.code != 0
doAssert refused.output.contains("not generated by wing"), refused.output
