## `wing template check / diff / update` — carrying template changes into projects already made.
##
## The comparison is three-way, and the third point is what `.wing.toml` records: what each file
## looked like when it was generated. With it, a file that differs from the template can be told
## apart into the two cases that matter -- the template moved, or you edited it -- and only the
## first is safe to overwrite without asking.
##
## The fresh copy is rendered by running `wing template apply` into a temporary directory rather
## than by re-implementing rendering here. Placeholders, flavours, config hooks and file filters all
## get applied exactly as they were the first time, because it is the same code doing it.

import std/[os, osproc, sequtils, streams, strutils]

import ../cliargs
import ../templates/provenance
import ../util

type
  Verdict* = enum
    vSame     ## the project has what the template would write
    vTemplate ## the template changed and this file was never touched here
    vLocal    ## edited here, and the template did not move
    vBoth     ## edited here *and* the template moved
    vAdded    ## the template has a file this project does not
    vRemoved  ## the project has a generated file the template no longer writes

  Change* = object
    rel*: string
    verdict*: Verdict
    rendered*: string ## path in the freshly rendered tree, when there is one

proc label(verdict: Verdict): string =
  case verdict
  of vSame: "up to date"
  of vTemplate: paint("update", "32")
  of vLocal: paint("yours", "36")
  of vBoth: paint("conflict", "33")
  of vAdded: paint("new", "32")
  of vRemoved: paint("gone from template", "35")

proc runWing(args: seq[string]): tuple[code: int; output: string] =
  let process = startProcess(getAppFilename(), args = args,
      options = {poStdErrToStdOut})
  let output = process.outputStream.readAll()
  let code = process.waitForExit()
  process.close()
  (code, output)

proc renderPristine(record: Provenance; into: string) =
  ## A clean generation of the same template, with the same answers.
  ##
  ## The bundled templates are materialised into the data directory when they are installed, and
  ## `apply` renders from that copy -- so an edit to the template tree is invisible until it is
  ## re-seeded. Doing it here is the difference between this command reporting template changes and
  ## reporting nothing at all, which is worse than not having the command.
  discard runWing(@["template", "builtins", "install", "--force"])
  var args = @["template", "apply", record.templateName, into,
      "--name", record.projectName, "--no-git", "--force"]
  if record.flavour.len > 0:
    args.add(@["--flavour", record.flavour])
  let rendered = runWing(args)
  if rendered.code != 0:
    die("could not render '" & record.templateName & "':\n" &
        rendered.output.strip(), 1)

proc compare*(record: Provenance; root, rendered: string): seq[Change] =
  ## Every file the template writes, plus the ones it used to.
  for rel in projectFiles(rendered):
    let hereFile = root / rel
    let freshHash = hashFile(rendered / rel)
    let generated = findHash(record, rel)
    if not fileExists(hereFile):
      result.add(Change(rel: rel, verdict: vAdded, rendered: rendered / rel))
      continue
    let hereHash = hashFile(hereFile)
    if hereHash == freshHash:
      result.add(Change(rel: rel, verdict: vSame))
    elif generated.len > 0 and hereHash == generated:
      # Untouched since it was generated, so the difference is entirely the template's.
      result.add(Change(rel: rel, verdict: vTemplate, rendered: rendered / rel))
    elif generated.len > 0 and generated == freshHash:
      # The template says what it always said; the difference is yours.
      result.add(Change(rel: rel, verdict: vLocal))
    else:
      result.add(Change(rel: rel, verdict: vBoth, rendered: rendered / rel))

  # A file the template used to write and no longer does. Reported, never deleted: it may have
  # become the project's own, and no template change is worth removing work.
  for entry in record.files:
    if not fileExists(rendered / entry.rel) and fileExists(root / entry.rel):
      result.add(Change(rel: entry.rel, verdict: vRemoved))

proc loadRecord(pathArg: string): tuple[root: string; record: Provenance] =
  let root = findProjectRoot(pathArg)
  if root.len == 0:
    die("No " & provenanceName & " here or above — this project was not generated by wing, " &
        "or predates it", 2)
  let record = parseProvenance(provenancePath(root))
  if record.templateName.len == 0:
    die(provenancePath(root) & " names no template", 2)
  (root, record)

proc summarize(changes: seq[Change]; root: string; record: Provenance): int =
  var counts: array[Verdict, int]
  for change in changes:
    counts[change.verdict].inc
  for change in changes:
    if change.verdict == vSame:
      continue
    echo " " & label(change.verdict) & repeat(" ",
        max(1, 20 - label(change.verdict).len)) & change.rel
  echo ""
  if counts[vTemplate] + counts[vAdded] + counts[vBoth] + counts[vRemoved] == 0:
    echo paint("Up to date with the " & record.templateName & " template.", "32")
    return 0
  echo $(counts[vTemplate] + counts[vAdded]) & " to update, " &
      $counts[vBoth] & " in conflict, " & $counts[vLocal] & " yours, " &
      $counts[vRemoved] & " no longer in the template"
  1

proc handleTemplateCheck*(argsIn: seq[string]) =
  var args = argsIn
  rejectUnknownOptions(args)
  let (root, record) = loadRecord(if args.len > 0: args[0] else: "")
  let rendered = getTempDir() / "wing-check-" & $getCurrentProcessId()
  removeDir(rendered)
  defer: removeDir(rendered)
  renderPristine(record, rendered)
  echo record.projectName & "  ·  " & record.templateName &
      (if record.flavour.len > 0: " (" & record.flavour & ")" else: "") &
      "  ·  generated " & record.generatedAt
  quit(summarize(compare(record, root, rendered), root, record))

proc handleTemplateDiff*(argsIn: seq[string]) =
  var args = argsIn
  rejectUnknownOptions(args)
  let (root, record) = loadRecord(if args.len > 0: args[0] else: "")
  let rendered = getTempDir() / "wing-diff-" & $getCurrentProcessId()
  removeDir(rendered)
  defer: removeDir(rendered)
  renderPristine(record, rendered)

  var shown = 0
  for change in compare(record, root, rendered):
    if change.verdict in [vSame, vLocal, vRemoved]:
      continue
    shown.inc
    echo paint("--- " & change.rel & "  (" & label(change.verdict) & ")", "1")
    # `diff` rather than a diff written here: everybody can already read its output, and it is on
    # every machine this runs on.
    # A file the project does not have yet has no left-hand side; /dev/null is what diff expects
    # there, and without it diff reports a missing file instead of showing what would arrive.
    let before = if change.verdict == vAdded: "/dev/null" else: root / change.rel
    discard execCmd("diff -u " & quoteShell(before) & " " &
        quoteShell(change.rendered) & " | tail -n +3")
  if shown == 0:
    echo "Nothing the template would change."

proc handleTemplateUpdate*(argsIn: seq[string]) =
  var args = argsIn
  let force = popFlag(args, ["--force"])
  let dryRun = popFlag(args, ["--dry-run", "-n"])
  rejectUnknownOptions(args)
  let (root, record) = loadRecord(if args.len > 0: args[0] else: "")
  let rendered = getTempDir() / "wing-update-" & $getCurrentProcessId()
  removeDir(rendered)
  defer: removeDir(rendered)
  renderPristine(record, rendered)

  let changes = compare(record, root, rendered)
  var applied, skipped = 0
  for change in changes:
    let wanted =
      case change.verdict
      of vTemplate, vAdded: true
      of vBoth: force
      else: false
    if not wanted:
      if change.verdict == vBoth:
        skipped.inc
      continue
    echo " " & label(change.verdict) & repeat(" ", max(1, 20 -
        label(change.verdict).len)) & change.rel
    if dryRun:
      applied.inc
      continue
    createDir(parentDir(root / change.rel))
    copyFile(change.rendered, root / change.rel)
    applied.inc

  if dryRun:
    echo ""
    echo $applied & " would change, " & $skipped & " left alone (--force to take those too)"
    return

  if applied > 0:
    # Only the files that were written get a new hash. Re-recording the whole tree would take every
    # file you had edited as "what the template wrote", and the next update would then see your work
    # as a template change and quietly revert it.
    var refreshed = record
    for change in changes:
      let took =
        case change.verdict
        of vTemplate, vAdded: true
        of vBoth: force
        else: false
      if not took:
        continue
      let fresh = hashFile(root / change.rel)
      var found = false
      for i in 0 .. refreshed.files.high:
        if refreshed.files[i].rel == change.rel:
          refreshed.files[i].hash = fresh
          found = true
          break
      if not found:
        refreshed.files.add((rel: change.rel, hash: fresh))
    writeProvenance(root, refreshed)
  echo ""
  if skipped > 0:
    echo $applied & " updated, " & $skipped &
        " left alone — they changed here too, `wing template diff` shows how " &
        "(--force overwrites)"
  else:
    echo $applied & " updated"
