name: release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - name: Build
        run: |
          nix develop --impure --command bash -c '
          mkdir -p target
          odin build src -out:target/{{kebab_name}} -o:speed'
