## Finding the projects on another machine.
##
## Local discovery walks the filesystem. There is no filesystem to walk here, so the walk happens
## over there: one `find` per machine, run remotely, answering with a marker file per line. One
## round trip for a whole machine, because the alternative is a round trip per candidate directory
## and a scan that takes minutes.

import std/[os, strutils, tables]

import ../types

const discoveryProbe* = """
root=%ROOT%
depth=%DEPTH%
find "$root" -mindepth 1 -maxdepth "$depth" \
  \( -name .git -o -name Cargo.toml -o -name go.mod -o -name '*.nimble' \
     -o -name pyproject.toml -o -name package.json -o -name build.zig \
     -o -name dub.json -o -name shard.yml -o -name meson.build \
     -o -name CMakeLists.txt -o -name xmake.lua -o -name dune-project \
     -o -name v.mod -o -name '*.cabal' -o -name .make.lua \) \
  -not -path '*/node_modules/*' -not -path '*/.direnv/*' -not -path '*/target/*' \
  -printf '%h\t%f\n' 2>/dev/null | sort -u
"""
  ## The same markers local discovery knows, asked for in one pass. `-printf '%h\t%f'` gives the
  ## directory and the marker separately, so the language can be told from the marker without
  ## parsing the path -- and `sort -u` collapses the several markers a polyglot project has.

proc probeFor*(root: string; depth: int): string =
  discoveryProbe.replace("%ROOT%", quoteShell(root)).replace("%DEPTH%", $depth)

proc languageOf*(marker: string): string =
  case marker
  of "Cargo.toml": "rust"
  of "go.mod": "go"
  of "pyproject.toml": "python"
  of "package.json": "node"
  of "build.zig": "zig"
  of "dub.json": "d"
  of "shard.yml": "crystal"
  of "dune-project": "ocaml"
  of "v.mod": "v"
  # `.make.lua` says a project was generated by wing, which is worth registering even when nothing
  # else in the directory says what it is written in.
  of ".make.lua": ""
  of "meson.build": "vala"
  of "CMakeLists.txt", "xmake.lua": "cpp"
  of ".git": ""
  else:
    if marker.endsWith(".nimble"): "nim"
    elif marker.endsWith(".cabal"): "haskell"
    else: ""

proc parseDiscovery*(machine, output: string; stamp: string): seq[Project] =
  ## One project per directory, whatever the markers say about it.
  ##
  ## A directory carrying `.git` *and* `Cargo.toml` is one project written in Rust, not two -- so
  ## the rows are folded by directory and the language is taken from the marker that names one.
  var languages = initOrderedTable[string, string]()
  for line in output.splitLines():
    let parts = line.split('\t', 1)
    if parts.len != 2:
      continue
    let directory = parts[0].strip()
    let marker = parts[1].strip()
    if directory.len == 0:
      continue
    let language = languageOf(marker)
    if directory notin languages:
      languages[directory] = language
    elif languages[directory].len == 0:
      languages[directory] = language

  for directory, language in languages:
    result.add(Project(
      name: directory.lastPathPart,
      path: directory,
      machine: machine,
      namespace: "default",
      language: language,
      tags: @[],
      createdAt: stamp,
      updatedAt: stamp
    ))

proc mergeDiscovered*(existing: var seq[Project]; found: seq[Project];
    stamp: string): tuple[added, updated: int] =
  ## Registered without duplicating: a project is the same one if it is the same path on the same
  ## machine. Re-running discovery is how the registry stays true, so it must be safe to repeat.
  for project in found:
    var matched = -1
    for i, known in existing:
      if known.machine == project.machine and known.path == project.path:
        matched = i
        break
    if matched < 0:
      existing.add(project)
      result.added.inc
    else:
      # The path and the machine are what identify it; everything else the probe learned is fresher
      # than what is on record, except a description someone wrote by hand.
      if existing[matched].language.len == 0 and project.language.len > 0:
        existing[matched].language = project.language
      existing[matched].updatedAt = stamp
      result.updated.inc
